### PR TITLE
Add support for server query string data after user login

### PR DESCRIPTION
**Pull request by 10h30**
Add support for server query string data after user login

### CODE REVIEW

**Comment by champsupertramp** [comment]
Hi @10h30,
Can you please provide example URL with your commit?
Why not use `add_query_arg( )` in query string concatenation?

**Comment by 10h30** [comment]
Hi @champsupertramp ,
The commit is following the discussion here: https://wordpress.org/support/topic/redirection-after-the-user-has-logged-in?replies=6

I use my Wordpress (with Ultimate Member) as SSO Login for Discourse. With the current UM code, the server query string is stripped down after login, user is not redirected back to Discourse after logging in.

Example: club.yeuchaybo.com

**Comment by champsupertramp** [comment]
@10h30 Thank you. Pushed into master repo.

**Comment by 10h30** [comment]
I realized that I added the code at wrong line. Already request another pull request to fix that.

**Pull request merged**
