### PR TITLE
Custom metadata for profile slug

### PR DESCRIPTION
**Pull request by fahelmoreira**
Add a option to use a custom metadata in the profile slug

### CODE REVIEW

**Comment by ravneetsinghkis** [comment]
https://prnt.sc/ritc8Wfh8wou
I merged your code to changes url slug functionality In ultimate plugin but your code not reflecting

**Comment by ravneetsinghkis** [comment]
Ok Thank you for this but I want to use base64 encoding value in url it will work for this

**Comment by deepukisworks** [comment]
I want to change my profile slug with my custom functionality. is  your code will work if I modify your file if yes can you please let me know how it will work I checked with above option is working fine but my URL is not working
https://prnt.sc/W2Mr8jWUtVfc

**Comment by fahelmoreira** [comment]
sure @deepukisworks, but did you create the custom field on the user profile page? and if so did you add the name as I did? btw the "profile_sug" it's just a placeholder for the name needs to be the same name as the field you created

**Comment by deepukisworks** [comment]
No, I just modified my plugin with your code and get results can you please let me know in brief means do i need to create custom field on profile page and what next step I have to follow

**Comment by nikitasinelnikov** [comment]
The ability to use custom user meta as slug is added here:
https://github.com/ultimatemember/ultimatemember/pull/1299

@ravneetsinghkis
There is also an added ability to set the user slug as hash string. Or if you need own encrypt the user slug please use this filter together with the "Custom usermeta" permalink base. https://github.com/ultimatemember/ultimatemember/pull/1299/files#diff-5f2f61ac3e24754e0d12d9b931d25a7daf0a0076acc16299ab3990d719fede20R803

**Pull request closed without merging**
