### PR TITLE
Unify getting templates for emails and shortcodes/pages layouts

### PR DESCRIPTION
**Pull request by yuriinalivaiko**
### Feature: Save email templates in uploads directory

Added: filter hook 'um_save_email_templates_to_uploads'
Added: filter hook 'um_email_template_filepath'
Modified: method UM()->mail()->copy_email_template( $template, $location );
Modified: method UM()->mail()->get_template_file( $location, $template_name );
Modified: method UM()->mail()->locate_template( $template_name );

**How to enable this feature**
Add code below to the file _functions.php_ in the active theme directory or where you need:
`add_filter( 'um_save_email_templates_to_uploads', '__return_true' );`

### CODE REVIEW

**Comment by nikitasinelnikov** [comment]
Hi @yuriinalivaiko 

`add_filter( 'um_save_email_templates_to_uploads', '__return_true' );`

This hook is very specific, could you rewrite the functions in the way that we have a variable e.g. `$basedir` and this dir will be handled by the hook and customers will be able to change the base folder for the templates. Maybe some of them want to save templates into their own files folder, etc.

**Comment by yuriinalivaiko** [comment]
### Feature: Save email templates in custom directory

**How to enable this feature**
Add code below to the file functions.php in the active theme directory or where you need:

Example 01 - Uploads directory
```
add_filter( 'um_save_email_templates_to', 'my_um_save_email_templates_to' );
function my_um_save_email_templates_to( $save_to ) {
  $save_to = 'uploads';
  return $save_to;
}
```

Example 02 - Custom directory
```
add_filter( 'um_save_email_templates_to', 'my_um_save_email_templates_to' );
function my_um_save_email_templates_to( $save_to ) {
  $save_to = trailingslashit( ABSPATH ) . 'um-templates';
  return $save_to;
}
```
**Note:** Custom directory must exist.

**Comment by nikitasinelnikov** [comment]
We need to make 1 place function to operate with all templates that we have in UM and extensions.

Please use this path [basedir][blog_id][locale][module_slug][template_name] for layouts
Please use this path [basedir][blog_id][locale]/emails/[email_template_name] for emails

**Comment by denisbaranov** [comment]
Ready for merge.
Description and testing instruction: [https://docs.google.com/document/d/1X2pcyaJWIgSxsJ-VZnLQvExnxo46HpzahNheizZ8gvo/edit?usp=sharing](https://docs.google.com/document/d/1X2pcyaJWIgSxsJ-VZnLQvExnxo46HpzahNheizZ8gvo/edit?usp=sharing)

**Comment by denisbaranov** [comment]
Closed by accident

**Pull request closed without merging**
