### PR TITLE
Fixed: UM links to empty phone numbers

### PR DESCRIPTION
**Pull request by yuriinalivaiko**
Issue: #1515 UM links to empty phone numbers

Empty field is displaying due to missing conditions. This condition fixes it;
```php
if ( empty( trim( str_replace( '+', '', $value ) ) ) ) {
  return '';
}
```
- str_replace( '+', '', $value ): Removes all + characters from $value.
- trim( ... ): Trims whitespace from the resulting string.
- empty( ... ): Checks if the resulting string is empty.

Also tel field was added and sanitized upon updating profile to other similar fields
```php
case 'tel':
```

### CODE REVIEW

**Comment by MissVeronica** [comment]
> so we could remove plus sign

Never remove the + sign from a telephone number as it's information for the caller's mobile
it's an international phone number and the phone is adding the caller's country's international prefix.

Example if I call the USA I will add `+1` where 1 is US country code to a local US number 
which the phone will translate to `0091` plus local number and the `009` is the international prefix.

Proper coding

```
if ( ! trim( str_replace( '+', '', $value ) ) ) {
   return '';
}
```

**Comment by yuriinalivaiko** [comment]
Condition updated

**Comment by MissVeronica** [comment]
Maybe this is better coding standard

```
if ( empty( trim( str_replace( '+', '', $value ) ) ) ) {
   return '';
}
```

**Comment by yuriinalivaiko** [comment]
Yes, I believe that's better.

**Pull request merged**
